export const ALLOWED_PRODUCT_SORT_FIELDS = ["price", "name", "created_at"];
export const ALLOWED_ORDERS = ["ASC", "DESC"];

export const ALLOWED_CATEGORY_SORT_FIELDS = ["name", "is_active"];

export const PostgresErrorCodes = {
  UNIQUE_VIOLATION: "23505",
  FOREIGN_KEY_VIOLATION: "23503",
  NOT_NULL_VIOLATION: "23502",
  CHECK_VIOLATION: "23514",
  EXCLUSION_VIOLATION: "23P01",
  INVALID_TEXT_REPRESENTATION: "22P02",
  NUMERIC_VALUE_OUT_OF_RANGE: "22003",
  STRING_DATA_RIGHT_TRUNCATION: "22001",
} as const;

export const TTL = {
  CART: 60 * 60,
  PRODUCTS: 60 * 5,
  CATEGORIES: 60 * 60 * 24,
};
